In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [5]:
from sklearn.datasets import load_digits

In [7]:
df=load_digits()

In [8]:
df.images.shape

(1797, 8, 8)

In [9]:
df.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [10]:
df.images[0].shape

(8, 8)

In [28]:
n_samples = len(df.images)
data=df.images.reshape((n_samples, -1))

In [39]:
data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [40]:
data[0].shape

(64,)

In [41]:
data.shape

(1797, 64)

In [15]:
data.min()

0.0

In [16]:
data.max()

16.0

In [17]:
data=data/16

In [18]:
data.min()

0.0

In [19]:
data.max()

1.0

In [20]:
data[0]

array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])

In [21]:
from sklearn.model_selection import train_test_split

In [29]:
x_train, x_test, y_train, y_test= train_test_split(data, df.target, test_size=0.3)

In [30]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1257, 64), (540, 64), (1257,), (540,))

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
rf=RandomForestClassifier()

In [33]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [34]:
y_pred = rf.predict(x_test)

In [42]:
y_pred

array([5, 6, 0, 6, 2, 2, 1, 4, 3, 3, 3, 4, 9, 3, 0, 4, 1, 2, 3, 4, 7, 6,
       8, 6, 2, 1, 6, 4, 8, 8, 9, 8, 5, 4, 7, 8, 3, 9, 8, 6, 5, 5, 0, 5,
       2, 7, 3, 6, 4, 8, 5, 6, 7, 0, 1, 3, 9, 9, 9, 8, 7, 9, 6, 7, 8, 9,
       9, 6, 8, 7, 3, 9, 1, 0, 0, 4, 7, 4, 5, 3, 1, 8, 1, 3, 4, 7, 7, 9,
       0, 7, 5, 4, 1, 4, 2, 3, 8, 0, 0, 1, 5, 9, 3, 1, 9, 8, 8, 0, 2, 3,
       9, 3, 4, 9, 9, 6, 3, 8, 3, 4, 1, 7, 1, 6, 1, 1, 1, 5, 3, 7, 7, 3,
       2, 3, 6, 7, 0, 4, 9, 1, 1, 2, 7, 4, 8, 5, 0, 3, 9, 6, 7, 9, 4, 4,
       7, 3, 0, 8, 7, 5, 0, 4, 8, 8, 1, 9, 4, 6, 4, 4, 2, 5, 2, 6, 0, 4,
       8, 3, 1, 6, 3, 1, 2, 3, 8, 1, 5, 6, 1, 2, 5, 9, 5, 6, 7, 0, 1, 6,
       2, 2, 7, 3, 5, 4, 1, 6, 6, 4, 7, 3, 2, 0, 5, 0, 6, 8, 4, 9, 1, 5,
       5, 6, 9, 3, 4, 0, 2, 9, 5, 9, 5, 4, 1, 4, 7, 4, 7, 9, 0, 7, 7, 7,
       6, 8, 4, 3, 0, 0, 8, 2, 6, 8, 8, 7, 9, 8, 5, 0, 9, 7, 1, 1, 3, 6,
       7, 4, 4, 5, 7, 4, 9, 5, 9, 1, 0, 1, 1, 3, 3, 1, 0, 8, 2, 9, 0, 3,
       5, 1, 6, 8, 7, 7, 3, 1, 8, 5, 9, 9, 1, 4, 5,

In [43]:
from sklearn.metrics import confusion_matrix, classification_report

In [46]:
confusion_matrix(y_test, y_pred)

array([[58,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 55,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 49,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0, 57,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 48,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 56,  0,  0,  1,  2],
       [ 0,  0,  0,  0,  0,  0, 45,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 52,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  1, 49,  0],
       [ 0,  0,  0,  2,  0,  0,  0,  1,  0, 59]], dtype=int64)

In [45]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        58
           1       0.96      1.00      0.98        55
           2       1.00      1.00      1.00        49
           3       0.97      0.97      0.97        59
           4       1.00      1.00      1.00        48
           5       1.00      0.95      0.97        59
           6       1.00      0.98      0.99        46
           7       0.96      1.00      0.98        52
           8       0.94      0.94      0.94        52
           9       0.97      0.95      0.96        62

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540

