In [ ]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('https://github.com/ybifoundation/Dataset/blob/main/Movies%20Recommendation.csv?raw=true')

In [ ]:
df.head()

Movie_ID      Movie_Title                       Movie_Genre Movie_Language  \
0         1       Four Rooms                      Crime Comedy             en   
1         2        Star Wars  Adventure Action Science Fiction             en   
2         3     Finding Nemo                  Animation Family             en   
3         4     Forrest Gump              Comedy Drama Romance             en   
4         5  American Beauty                             Drama             en   

   Movie_Budget  Movie_Popularity Movie_Release_Date  Movie_Revenue  \
0       4000000         22.876230         09-12-1995        4300000   
1      11000000        126.393695         25-05-1977      775398007   
2      94000000         85.688789         30-05-2003      940335536   
3      55000000        138.133331         06-07-1994      677945399   
4      15000000         80.878605         15-09-1999      356296601   

   Movie_Runtime  Movie_Vote  ...  \
0           98.0         6.5  ...   
1          121.0         8.1  ...   
2          100.0         7.6  ...   
3          142.0         8.2  ...   
4          122.0         7.9  ...   

                                      Movie_Homepage  \
0                                                NaN   
1  http://www.starwars.com/films/star-wars-episod...   
2              http://movies.disney.com/finding-nemo   
3                                                NaN   
4                      http://www.dreamworks.com/ab/   

                                      Movie_Keywords  \
0          hotel new year's eve witch bet hotel room   
1        android galaxy hermit death star lightsaber   
2  father son relationship harbor underwater fish...   
3  vietnam veteran hippie mentally disabled runni...   
4  male nudity female nudity adultery midlife cri...   

                                      Movie_Overview  \
0  It's Ted the Bellhop's first night on the job....   
1  Princess Leia is captured and held hostage by ...   
2  Nemo, an adventurous young clownfish, is unexp...   
3  A man with a low IQ has accomplished great thi...   
4  Lester Burnham, a depressed suburban father in...   

                              Movie_Production_House  \
0  [{"name": "Miramax Films", "id": 14}, {"name":...   
1  [{"name": "Lucasfilm", "id": 1}, {"name": "Twe...   
2     [{"name": "Pixar Animation Studios", "id": 3}]   
3          [{"name": "Paramount Pictures", "id": 4}]   
4  [{"name": "DreamWorks SKG", "id": 27}, {"name"...   

                            Movie_Production_Country  \
0  [{"iso_3166_1": "US", "name": "United States o...   
1  [{"iso_3166_1": "US", "name": "United States o...   
2  [{"iso_3166_1": "US", "name": "United States o...   
3  [{"iso_3166_1": "US", "name": "United States o...   
4  [{"iso_3166_1": "US", "name": "United States o...   

                      Movie_Spoken_Language  \
0  [{"iso_639_1": "en", "name": "English"}]   
1  [{"iso_639_1": "en", "name": "English"}]   
2  [{"iso_639_1": "en", "name": "English"}]   
3  [{"iso_639_1": "en", "name": "English"}]   
4  [{"iso_639_1": "en", "name": "English"}]   

                                       Movie_Tagline  \
0  Twelve outrageous guests. Four scandalous requ...   
1       A long time ago in a galaxy far, far away...   
2  There are 3.7 trillion fish in the ocean, they...   
3  The world will never be the same, once you've ...   
4                                       Look closer.   

                                          Movie_Cast  \
0  Tim Roth Antonio Banderas Jennifer Beals Madon...   
1  Mark Hamill Harrison Ford Carrie Fisher Peter ...   
2  Albert Brooks Ellen DeGeneres Alexander Gould ...   
3  Tom Hanks Robin Wright Gary Sinise Mykelti Wil...   
4  Kevin Spacey Annette Bening Thora Birch Wes Be...   

                                          Movie_Crew   Movie_Director  
0  [{'name': 'Allison Anders', 'gender': 1, 'depa...   Allison Anders  
1  [{'name': 'George Lucas', 'gender': 2, 'depart...     George Lucas  
2  [{'na

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Movie_ID                  4760 non-null   int64  
 1   Movie_Title               4760 non-null   object 
 2   Movie_Genre               4760 non-null   object 
 3   Movie_Language            4760 non-null   object 
 4   Movie_Budget              4760 non-null   int64  
 5   Movie_Popularity          4760 non-null   float64
 6   Movie_Release_Date        4760 non-null   object 
 7   Movie_Revenue             4760 non-null   int64  
 8   Movie_Runtime             4758 non-null   float64
 9   Movie_Vote                4760 non-null   float64
 10  Movie_Vote_Count          4760 non-null   int64  
 11  Movie_Homepage            1699 non-null   object 
 12  Movie_Keywords            4373 non-null   object 
 13  Movie_Overview            4757 non-null   object 
 14  Movie_Pr

In [ ]:
df.dropna()

Movie_ID                                        Movie_Title  \
1            2                                          Star Wars   
2            3                                       Finding Nemo   
4            5                                    American Beauty   
9           10  Pirates of the Caribbean: The Curse of the Bla...   
10          11                                  Kill Bill: Vol. 1   
...        ...                                                ...   
4728      4755                                     Time to Choose   
4737      4765                                           Bad Moms   
4743      4772                                       Fight Valley   
4745      4774                                              Kicks   
4748      4777                                      The Dog Lover   

                           Movie_Genre Movie_Language  Movie_Budget  \
1     Adventure Action Science Fiction             en      11000000   
2                     Animation Family             en      94000000   
4                                Drama             en      15000000   
9             Adventure Fantasy Action             en     140000000   
10                        Action Crime             en      30000000   
...                                ...            ...           ...   
4728                       Documentary             en       3500000   
4737                            Comedy             en      20000000   
4743                      Action Drama             en      27000000   
4745                         Adventure             en             0   
4748                             Drama             en       2000000   

      Movie_Popularity Movie_Release_Date  Movie_Revenue  Movie_Runtime  \
1           126.393695         25-05-1977      775398007          121.0   
2            85.688789         30-05-2003      940335536          100.0   
4            80.878605         15-09-1999      356296601          122.0   
9           271.972889         09-07-2003      655011224          143.0   
10           79.754966         10-10-2003      180949000          111.0   
...                ...                ...            ...            ...   
4728          1.618138         04-09-2015              0          100.0   
4737         42.512296         28-07-2016      183936074          100.0   
4743          1.224105         22-07-2016              0           90.0   
4745          3.467923         09-09-2016              0           80.0   
4748          1.193219         08-07-2016              0          101.0   

      Movie_Vote  ...                                     Movie_Homepage  \
1            8.1  ...  http://www.starwars.com/films/star-wars-episod...   
2            7.6  ...              http://movies.disney.com/finding-nemo   
4            7.9  ...                      http://www.dreamworks.com/ab/   
9            7.5  ...  http://disney.go.com/disneyvideos/liveaction/p...   
10           7.7  ...   http://www.miramax.com/movie/kill-bill-volume-1/   
...          ...  ...                                                ...   
4728         0.0  ...                        http://www.timetochoose.com   
4737         6.3  ...                      http://stxmovies.com/badmoms/   
4743         3.9  ...                        http://www.fightvalley.com/   
4745         7.5  ...                 http://www.focusfeatures.com/kicks   
4748         5.3  ...                   http://www.thedoglovermovie.com/   

                                         Movie_Keywords  \
1           android galaxy hermit death star lightsaber   
2     father son relationship harbor underwater fish...   
4     male nudity female nudity adultery midlife cri...   
9     exotic island blacksmith east india trading co...   
10           japan coma martial arts kung fu underworld   
...                                                 ...   
4728                         climate change documentary   
4737                   alcohol bar par

In [ ]:
df_features = df[['Movie_Genre','Movie_Spoken_Language','Movie_Keywords','Movie_Production_Country','Movie_Cast']]

In [ ]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Movie_Genre               4760 non-null   object
 1   Movie_Spoken_Language     4760 non-null   object
 2   Movie_Keywords            4373 non-null   object
 3   Movie_Production_Country  4760 non-null   object
 4   Movie_Cast                4733 non-null   object
dtypes: object(5)
memory usage: 186.1+ KB


In [ ]:
df_features = df_features.dropna()

In [ ]:
X = df_features['Movie_Genre']+' '+df_features['Movie_Spoken_Language']+' '+df_features['Movie_Keywords']+' '+df_features['Movie_Production_Country']+' '+df_features['Movie_Cast']

In [ ]:
X

0       Crime Comedy [{"iso_639_1": "en", "name": "Eng...
1       Adventure Action Science Fiction [{"iso_639_1"...
2       Animation Family [{"iso_639_1": "en", "name": ...
3       Comedy Drama Romance [{"iso_639_1": "en", "nam...
4       Drama [{"iso_639_1": "en", "name": "English"}]...
                              ...                        
4751    Horror [{"iso_639_1": "en", "name": "English"}...
4752    History Drama War Action [{"iso_639_1": "en", ...
4754    Action Adventure Animation Family Fantasy [{"i...
4757    Thriller Drama [{"iso_639_1": "en", "name": "E...
4759    Documentary [] music actors legendary perfomer...
Length: 4364, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(X)

In [ ]:
X

<4364x12947 sparse matrix of type '<class 'numpy.float64'>'
	with 135313 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

Similarity_Score = cosine_similarity(X)

In [ ]:
print(Similarity_Score)

Similarity_Score.shape

[[1.         0.01969064 0.01783883 ... 0.1286528  0.02294662 0.00632509]
 [0.01969064 1.         0.01752695 ... 0.05266349 0.02254544 0.00621451]
 [0.01783883 0.01752695 1.         ... 0.05338339 0.02042515 0.00563006]
 ...
 [0.1286528  0.05266349 0.05338339 ... 1.         0.0284045  0.00804361]
 [0.02294662 0.02254544 0.02042515 ... 0.0284045  1.         0.00724212]
 [0.00632509 0.00621451 0.00563006 ... 0.00804361 0.00724212 1.        ]]


(4364, 4364)

In [ ]:
Fav_Movie_Name = input('Enter your favourite movie name:')

Enter your favourite movie name:spiderman


In [ ]:
All_Movies_Title = df['Movie_Title'].tolist()

In [ ]:
import difflib as dl

Movie_Recommendation =  dl.get_close_matches(Fav_Movie_Name,All_Movies_Title)

In [ ]:
print(Movie_Recommendation)

Close_Match = Movie_Recommendation[0]

['Spider-Man', 'Superman', 'Spider-Man 3']


In [ ]:
Index_of_Close_Match_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)
Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)
len(Recommendation_Score)

231
[(0, 0.025046310266734075), (1, 0.04158885208666744), (2, 0.02229411583159477), (3, 0.02486417376721317), (4, 0.023855750629954903), (5, 0.06302418206446646), (6, 0.07114850038084441), (7, 0.018083602920389154), (8, 0.018769603451204958), (9, 0.05228249514977825), (10, 0.08088073560945828), (11, 0.03952627789346703), (12, 0.06905877694112392), (13, 0.02507046149098188), (14, 0.022402515683021363), (15, 0.1908942319215686), (16, 0.025455807556996363), (17, 0.057840751224626036), (18, 0.15543824748220542), (19, 0.040586985833940145), (20, 0.02572567625181943), (21, 0.03532345144646637), (22, 0.01626189172822554), (23, 0.032334387202623716), (24, 0.029397242090713552), (25, 0.02922092688395844), (26, 0.023707426366770142), (27, 0.034314321470198014), (28, 0.08316153096363874), (29, 0.07256903209566962), (30, 0.07494280008848161), (31, 0.05768062966276718), (32, 0.026753076542729477), (33, 0.06314552053317903), (34, 0.024686806671904156), (35, 0.05205458159291453), (36, 0.0417750343131

4364

In [ ]:
Sorted_Similar_Movies = sorted(Recommendation_Score,key=lambda x:x[1],reverse=True)
print(Sorted_Similar_Movies)

[(231, 1.0), (230, 0.4549575402691792), (229, 0.33335192900487354), (2860, 0.23321745339948768), (121, 0.2153523121937681), (3531, 0.21113700020227025), (2962, 0.20687229603360968), (84, 0.20152440751063602), (1755, 0.19990467141566623), (2448, 0.19767665254839814), (4170, 0.19578034004871525), (15, 0.1908942319215686), (3273, 0.187786950274002), (274, 0.18324246669863187), (1152, 0.1821586999766516), (1780, 0.17893638231569597), (1724, 0.17875892792749068), (1792, 0.17822592314318444), (1975, 0.17731441792103536), (1896, 0.17277891660743874), (4165, 0.1719130346972241), (180, 0.17176295942688233), (3479, 0.17023037143748998), (1360, 0.1672567261736277), (4184, 0.1664065844249404), (1392, 0.16615742043443021), (3527, 0.16536434109561865), (203, 0.1653373284300302), (2953, 0.1643361639695936), (1683, 0.16425875742021046), (1928, 0.1623475412615689), (4043, 0.16216639727718513), (596, 0.161799612577368), (584, 0.16138791780816622), (2029, 0.1613101232636893), (489, 0.16056018730890376), 

In [ ]:
print("Top 5 Movies Suggested for You:\n")
i=1
for movie in Sorted_Similar_Movies:
  index = movie[0]
  title_from_index=df[df.index == index]['Movie_Title']. values[0]
  if(i<6):
               print(i,'.',title_from_index)
               i+=1

Top 5 Movies Suggested for You:

1 . Spider-Man 2
2 . Spider-Man
3 . Fight Club
4 . Six-String Samurai
5 . Cat on a Hot Tin Roof
